// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaeNjCja5YKYOpO5RZXkhzyLE464MRvcg',
    appId: '1:262809061799:web:16e80ee860e93d47c04e82',
    messagingSenderId: '262809061799',
    projectId: 'schoolfresh',
    authDomain: 'schoolfresh.firebaseapp.com',
    storageBucket: 'schoolfresh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-fMcy14gQeeqJ1ruFFEx6LIEAFqGp_Lo',
    appId: '1:262809061799:android:b2f711582fc34e9ec04e82',
    messagingSenderId: '262809061799',
    projectId: 'schoolfresh',
    storageBucket: 'schoolfresh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgawVshqM94dlnVC29geTGmU7DJoqVnSw',
    appId: '1:262809061799:ios:8859f22820a374a4c04e82',
    messagingSenderId: '262809061799',
    projectId: 'schoolfresh',
    storageBucket: 'schoolfresh.appspot.com',
    iosClientId: '262809061799-cehthr4g093rm81k4i7b6lln6n4kcc19.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolUi',
  );
}
